@startuml inline_umlgraph_1.png

@enduml
@startuml uml_pending_transaction.png
participant GradidoBlockchainConnector as connector
database iota
participant GradidoNode as node
connector -> iota: Gradido Transaction
activate iota
activate connector
iota --> connector: iota message id
deactivate iota
connector -> connector: Store PendingTransaction with iota message id in list
deactivate connector
node -> iota: ask for new transactions [loop]
activate iota
iota --> node: return new transactions
deactivate iota
node -> node: validate transaction 
activate node
node -> connector: /notify with GradidoBlock or error message
deactivate node
activate connector
connector -> connector: search transaction in list and update it if found
deactivate connector
@enduml
